development:
  app_id: "104557599881620"
  secret: "fd50d665a0a813e8b4d67082b4bd1c1d"
  oauth_token: "CAACEdEose0cBACSZB4kmtX6ON2ZCBhH0Yo3SGK3ZAiCfMryeoL3Lm1aBD4f4hnCGuq2VtX9whIHmN4lO9f4zMZAHGcXXhNZBvIoOvqFC1MqZAnmSTZAFmQ31hMZBLbuCzYhtFZCYB7SWloruK0w68iy88xhUZBBRZB8cIUnksOXiGAvxq5pFuDvXcLo6fnJRVeopjLAnXpVh6xQJ5OkjnFMwSTk"