require "koala"

class UserController < ApplicationController
  
  	def index
      @adsFromYou = Ad.find_by_sql(["select * from users JOIN ads ON users.id = ads.user_id WHERE users.id = ?" , session[:user_id]])
      @adsFromOthers = Ad.find_by_sql(["select * from users JOIN ads ON users.id = ads.user_id WHERE users.id != ?" , session[:user_id]])
      
      @user_info_from_facebook = User.facebook
      @user_info_from_facebook = @user_info_from_facebook.api("/me?fields=id,name,website,birthday,quotes")
      
    end

  	def new
  		@user = User.new({:location => "Lahore" })
  	end

  	def create
  		@user = User.new(user_params)
	    if @user.save
	    	flash[:notice] = "User created Successfully"
	    	redirect_to(:controller => 'access' , :action => 'login')
	    else
	      	render('new')
	    end
  	end

  	def show
  		@user = User.find(params[:id])
  	end

    def update_rating
      @ad = Ad.find(params[:id])
      @user = User.find(@ad.user_id)
    end

    def update
      @user = User.find(params[:id])
      
      if @user.update_attributes( rating: params[:user][:rating] )
        flash[:notice] = "User Updated Successfully"
        redirect_to(:controller => 'user' , :action => 'index')
      else
        flash[:notice] = "User couldn't be updated"
        redirect_to(:controller => 'user' , :action => 'update_rating')
      end
    end

    def account 
      @oauth = Koala::Facebook::OAuth.new(FB_APP_ID, FB_APP_SECRET, 'http://localhost:3000/user/index') 
      user_id = @oauth.get_user_from_cookies(cookies) # gets the user's ID 
      user_info = @oauth.get_user_info_from_cookies(cookies) # parses and returns the entire hash 
      access_token = user_info["access_token"] 
      # generate authenticating URL 
      auth_url = @oauth.url_for_oauth_code 
      # hit the authenticating URL url generated by @oauth.url_for_oauth_code it will redirect to ur call back page with 'code' parameter. copy & paste the code to code variable 
      code = "b5b61e003e4d0565285e68aa-1160256180|v2DFQ5gUWKxucmYuqiN1h847N4s" 
      # fetch the access token once you have the code 
      oauth_access_token = @oauth.get_access_token(code) 
      # initialize a Graph API connection, for instance 
      @graph = Koala::Facebook::GraphAPI.new(oauth_access_token) 
      #Fetch user profile data 
      #profile = @graph.get_object("me") 
      #Fetch user's friend list 
      #friends = @graph.get_connections("me", "friends") 
      #Write into user's wall or friend feed 
      @graph.put_object("me", "feed", :message => "I am writing on my wall!") 

    end 

  	def user_params
      params.require(:user).permit(:firstName, :lastName, :email , :password , :location, :rating)
    end
end
